[template]
cargo_generate_version = ">=0.16.0"

[hooks]
post = ["final-msg.rhai"]

[placeholders]
tokio = { type = "bool", prompt = "Use Tokio?", default = false }

[conditional.'within_cargo_project == false'.placeholders]
ide = { type = "string", prompt = "Which IDE to use?", default = "vscode", choices = ["none", "vscode"] }

[conditional.'tokio != true']
ignore = [".cargo"]

[conditional.'within_cargo_project']
ignore = [
    ".github",
    ".vscode",
    ".gitignore",
]

[conditional.'within_cargo_project == false && ide != "vscode"']
ignore = [".vscode"]
